### ISSUE TITLE
Module not building.

### ISSUE THREAD

**Issue by mattpilott** [jbeuckm/TiBeacons#19]
Hi I have downloaded the module and imported it into Titanium however when i try to package it i get the following error:

Traceback (most recent call last):
  File "/Users/Matt/Desktop/- App Design -/TiBeacons/build.py", line 220, in <module>
    build_module(manifest,config)
  File "/Users/Matt/Desktop/- App Design -/TiBeacons/build.py", line 165, in build_module
    from tools import ensure_dev_path
ImportError: No module named tools

**Comment by wallanoo** [comment]
Hi  matt3224 , how do you have solvedthis issue? I have the same error

thanks

**Comment by matt3224** [comment]
If i remember rightly I cleared the build folder and rebuilt. You could try removing the module entirely and re-adding it. Also if you need 0.9.3 (64-bit compatible) you can grab it here http://www.creativelittledots.co.uk/org.beuckman.tibeacons-iphone-0.9.3.zip

**Comment by wallanoo** [comment]
thanks a lot!

Ric

2015-02-26 13:16 GMT+01:00 Matt Pilott <notifications@github.com>:
