### ISSUE TITLE
how to obtain the up-to-date module

### ISSUE THREAD

**Issue by wallanoo** [jbeuckm/TiBeacons#32]
Hi

sorry but I'm quite new on github and titanium modules

I've seen in the repo that the last changes are made within 5 months ago, but the last version of the module (org.beuckman.tibeacons-iphone-0.9.2.zip) is made 7 months ago.

it is possible to have an updated version?

specifically, I'm trying to obtain beacon notifications when the app is in background (more than 20-30 minutes) in IOS8

thanks a lot in advance

Ric

**Comment by h3r2on** [comment]
you can do your own build of any module from source. from the docs: http://docs.appcelerator.com/titanium/3.0/#!/guide/iOS_Module_Quick_Start-section-43288582_iOSModuleQuickStart-BuildandPackagetheModule

**Comment by wallanoo** [comment]
Hi

thanks

I've run the build.py in the TiBeacons-master folder as the webpage says,
but I obtain the following error, maybe I miss something?

Traceback (most recent call last):
  File "build.py", line 220, in <module>
    build_module(manifest,config)
  File "build.py", line 165, in build_module
    from tools import ensure_dev_path
ImportError: No module named tools

Ric

2015-02-25 20:41 GMT+01:00 Joel Herron <notifications@github.com>:

**Comment by chmiiller** [comment]
Hi there,
I've got it!
Built today with the last version of the module and Titanium 3.5.0:

https://www.dropbox.com/s/1mk2qzyggarztwc/org.beuckman.tibeacons-iphone-0.9.2.zip?dl=0

It would be nice to update the repository with this last version
